### ISSUE TITLE
Setup on boot2docker - no data to graphite

### ISSUE THREAD

**Issue by hbokh** [sitespeedio/sitespeed.io-docker#1]
Hi,
Could you please explain if this could / should work on boot2docker? I'm having some issues.
I start both graphite and grafana through docker-compose using this `docker-compose.yml`:

```
graphite:
  image: sitespeedio/graphite
  ports:
    - "8080:80"
    - "2003:2003"
grafana:
  image: grafana/grafana
  ports:
    - "80:3000"
```

But when I run:

`docker run --privileged --rm -v $PWD/sitespeed.io:/sitespeed.io sitespeedio/sitespeed.io sitespeed.io -u http://somesite -b firefox -n 2 --connection cable --graphiteHost boot2docker -m 5 --graphiteNamespace somesite`

I get this error:

`error: Couldn't send data to Graphite:Error: getaddrinfo ENOTFOUND for host:boot2docker port:2003`

However I can connect to port 2003 when using `boot2docker:2003`:

```
telnet boot2docker 2003
Trying 192.168.59.103...
Connected to boot2docker.
Escape character is '^]'.
^]
telnet> q
Connection closed.
```

FYI: _boot2docker_ is an entry in `/etc/hosts`, pointing to 192.168.59.103.
